-- 建立座位表
CREATE TABLE SeatingChart (
    FLOOR_SEAT_SEQ INT IDENTITY(1,1) PRIMARY KEY,
    FLOOR_NO INT,
    SEAT_NO INT
);

-- 建立員工表
CREATE TABLE Employee (
    EMP_ID VARCHAR(5) PRIMARY KEY,
    EMP_NAME NVARCHAR(50),
    FLOOR_SEAT_SEQ INT NULL
);